name: Update Countdown

on:
  schedule:
    - cron: "0 * * * *"  # har soatda yangilanadi
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run countdown script
        run: python .github/scripts/countdown.py

      - name: Update README
        run: |
          CONTENT=$(cat countdown.txt)
          sed -i "/⏱ Time Remaining:/c\⏱ Time Remaining: $CONTENT" README.md

      - name: Commit changes
        run: |
          git config --global user.name "amonovlazizbek"
          git config --global user.email "amonovlazizbek9@gmail.com"
          git add README.md
          git commit -m "update countdown" || exit 0
          git push